export const IA_CONFIG = {
  populationSize: 32,
  maxGenerations: 200,
  maxSteps: 360,
  fixedDelta: 1000 / 60,
  tournamentSize: 2,
  eliteSize: 1,
  crossoverAlpha: 0.2,
  mutationSigma: 0.08,
  mutationRate: 1 / 8,
  plateauLimit: 10,
  randomImmigrantRate: 0.05,
  hillClimbEvery: 5,
  hillClimbNeighbors: 4,
  hillClimbSigma: 0.03,
  adaptiveSigmaMedium: 0.14,
  adaptiveSigmaHigh: 0.18,
  diversityLowThreshold: 0.12,
};
